### ISSUE TITLE
출석표

### ISSUE THREAD

**Issue by sungsu9022** [sungsu9022/study-effective-java-3e#8]
## 출석표

| 출석 | 박성수 | 김래선 | 윤지수 | 조민혜 | 지성인 | 양성만 |
|------|--------|--------|--------|--------|--------|--------|
| 2/14 |    V    |   V     |  V      |  지각      |  V      |  V      |
| 2/21 |    V   |    지각    |   V     |    지각    |   지각     |    개인 사정으로 인한 불참    |
| 3/7  |     V    |   V    |   지각     |    V    |    V    |     V   |
| 3/21 |    V   |    V    |   V    |   사정으로 불참     |   V      |   V     |
| 3/28 |   V    |   V    |   불참     |    V    |    V    |    V    |
| 4/18 |   사정으로 불참    |   불참     |  불참      |  불참      |   V     |   V     |
| 4/24  |  사정으로 불참      |    불참   |     V  |     V   |    불참    |    V    |
| 5/9 |   V     |    V    |    V    |   V     |   V     |     V   |

### 보증금 지불 방식
- 일일 참석 : 5000원
- 지각시 : 2500원
- 불참시 0원

### 보증금 지급일
 - 스터디 종료일

**Comment by sungsu9022** [comment]
### 박성수
 - 불참 2회(- 10000원)
 - 40,000원

### 김래선
 - 지각 1회, 불참 2회(-12500원)
 - 37,500원

### 윤지수
 - 지각 1회, 불참 2회(-12500원)
 - 37,500원

### 조민혜
 - 지각 2회, 불참 2회(-15000원)
 - 35,000원

### 지성인
 - 지각 1회, 불참 1회(-7500원)
 - 42,500원

### 양성만
 - 불참 1회(-5000원)
 - 45,000원

### 불참/지각으로 인한 공용비용
 - 62,500원

**Comment by sungsu9022** [comment]
## 쫑파티 정산
 -  1차 얼룩도야지 147,320원
 - 2차 안주의신 59,000원
 - 합계 : 206,320원

### 공용비용으로부터 계산
 - 206,320 - 62,500 = 143,820원

### N빵
 - 143,820 / 6 = 23970원

### 각각 보증금으로부터 정산 후 돌려받는 금액
 - 박성수 40,000 - 23970 = 16,030
 - 김래선 37,500 - 23970 = 13,530
 - 윤지수 37,500 - 23970 = 13,530
 - 조민혜 35,000 - 23970 = 110,30
 - 지성인 42,500 - 23970 = 18,530
 - 양성만 45,000 - 23970 = 21,030

**Comment by iamsunk** [comment]
@sungsu9022 저 24일날 불참이요!

**Comment by sungsu9022** [comment]
입금 완료
